---
# tasks file for duplicity-backup
- name: Ensure duplicity is installed
  become: true
  package:
    name: duplicity
    state: present

- name: Ensure required python3 packages are installed
  pip:
    name:
      - botocore
      - boto3
      - b2sdk

- name: Ensure env file config is present
  template:
    src: templates/duplicity-envs.j2
    dest: "{{duplicity_working_dir}}/{{ duplicity_env_file }}"
    owner: root
    mode: "0600"

- name: Ensure include-list is present
  template:
    src: templates/include-list.j2
    dest: "{{ duplicity_working_dir }}/{{ duplicity_include_file }}"
    owner: root
    mode: "0600"

- name: Ensure backup script is present
  template:
    src: templates/duplicity-script-backup.j2
    dest: "{{ duplicity_working_dir }}/{{ duplicity_backup_script }}"
    mode: u+rx

- name: Ensure restore script is present
  template:
    src: templates/duplicity-script-restore.j2
    dest: "{{ duplicity_working_dir }}/{{ duplicity_restore_script }}"
    mode: u+rx

- name: Ensure cronjob is present
  ansible.builtin.cron:
    name: "run duplicity backup"
    minute: "0"
    hour: "1"
    user: root
    job: "{{ duplicity_working_dir }}/{{ duplicity_backup_script }}"
  when: duplicity_backup_script
